version: "3.9"
services:
  ipfs_1:
    image: "nodetest"
    network_mode: "net_1"
    volumes:
      - node_1:/root:rw
      - node_1_data:/root/.ipfs:rw
    command: "/root/start.sh"
    
volumes:
  node_1:
  node_1_data:
