version: "3.9"
services:
  ipfs_1:
    image: "alepart/ipfs_persistent_node"
    network_mode: "net_1"
    volumes:
      - node_1:/root:rw
      - node_1_data:/root/.ipfs:rw
    command: "/root/start.sh"
    
volumes:
  node_1:
    external: true
  node_1_data:
