version: "3.9"
services:
  ipfs_1:
    image: "alepart/ipfs_persistent_node"
    network_mode: "net_1"
    volumes:
      - node_1:/root:rw
      - ipfs_persistent_node_node_1_data:/root/.ipfs:rw
    command: "/root/start.sh"
    
  ipfs_2:
    image: "alepart/ipfs_persistent_node"
    network_mode: "net_2"
    volumes:
      - node_2:/root:rw
      - ipfs_persistent_node_node_2_data:/root/.ipfs:rw
    command: "/root/start.sh"


volumes:
  node_1:
    external: true
  ipfs_persistent_node_node_1_data:
  node_2:
    external: true
  ipfs_persistent_node_node_2_data:
  
